### ISSUE TITLE
关于多尺度的疑惑

### ISSUE THREAD

**Issue by Dandelion111** [Keep-Passion/GACN#1]
您好，您的网络中并没有进行下采样，为什么也可以称作多尺度？

**Comment by Keep-Passion** [comment]
> 您好，您的网络中并没有进行下采样，为什么也可以称作多尺度？

您好，您可以尝试着从感受野的角度理解多尺度。比如3*3的卷积层感受野是3*3，再来一层3*3卷积层感受野扩大到5*5。不论池化或者是多层卷积核，目标都是扩大感受野的尺度大小。这个网络里面有个核心操作是融合多层卷积层的输出结果，蕴含着多尺度融合的意思。这样方便您的理解吗？

**Comment by Dandelion111** [comment]
明白了，多谢！
