### ISSUE TITLE
请问一下，训练集怎么生成

### ISSUE THREAD

**Issue by ReckonerInheritor** [Keep-Passion/GACN#2]

**Comment by MrYYYYYYYYYYY** [comment]
您好，我们的训练集与测试集按照以下方式生成：
1、选取coco2014数据集中实例分割前景只有单个对象的图像
2、进一步选择前景对象大小在20000-170000像素之间的图像，并生成图象对应的分割mask
以上两步得到图像集按照7:3的比例分为训练集与测试集。对于训练集来说分为两个文件：train与mask_train。train中存放图像数据，mask_train中存放图像数据对应的分割mask。在训练时利用图像与其分割mask进行不同程度高斯模糊操作，分别生成前景模糊和背景模糊的图像对进行训练。
